#!/usr/bin/env bash

[[ -f $JOT_HOME/.env ]] && source $JOT_HOME/.env

JOT_HOME="${JOT_HOME:-.}"
JOT_EDITOR=${JOT_EDITOR:-$EDITOR}
JOT_DATE_FMT=${JOT_DATE_FMT:-%Y-%m-%d}
JOT_EXT=txt

# Drop trailing /
JOT_HOME="${JOT_HOME%/}"

check_file_exists() {
  if [[ ! -f "$1" ]]; then
    echo "File does not exist: $1"
    exit 1
  fi
}

parse_date() {
  case $1 in
    td|today|'')
      date +$JOT_DATE_FMT
      ;;
    y|yd|yesterday)
      date -d yesterday +$JOT_DATE_FMT
      ;;
    tm|tommorow)
      date -d tomorrow +$JOT_DATE_FMT
      ;;
    *)
      $1
      ;;
  esac
}

file_from_date() {
  echo "$JOT_HOME/$1.$JOT_EXT"
}

cmd_cat() {
  local date="$1"
  local file="$(file_from_date $date)"

  check_file_exists $file

  basename "$file" .$JOT_EXT
  echo
  cat "$file"
}

cmd_edit() {
  local date="$1"
  local file="$(file_from_date $date)"

  echo "Editing $file"
  echo
  echo 'Press any key to continue'
  read

  if [[ -f $file ]]; then
    sh -c "$JOT_EDITOR $JOT_EDIT_OPTS $file"
  else
    sh -c "$JOT_EDITOR $JOT_NEW_OPTS $file"
  fi
}

cmd_list() {
  echo "Today is $(date +'%a, %d %b %Y')"
  echo
  ls "$JOT_HOME"/*.$JOT_EXT | xargs -n 1 basename
}

case $1 in
  e|ed|edit|'')
    date="$(parse_date $2)"
    cmd_edit "$date"
    exit
    ;;
  c|cat)
    date="$(parse_date $2)"
    cmd_cat "$date"
    exit
    ;;
  l|ls|list)
    cmd_list
    exit
    ;;
  *)
    echo "Unrecognized command: $1"
    exit 1
    ;;
esac
